### ISSUE TITLE
wgd_syn i-adhore error

### ISSUE THREAD

**Issue by mellamosummer** [heche-psb/wgd#42]
Hello! I was able to generate a ks plot using wgd_dmd and wgd_ksd, but ran into some errors trying to run wgd_syn. A folder is still created with the following files: G_mac_hap1_CDS.fa.lists  G_mac_hap1_CDS.fa_gene_order_perchrom.tsv  families.tsv  gene-table.csv  iadhore.conf, but it looks like wgd_syn did not completely finish. 

Here's stdout: 
```
2024-08-23 12:50:50 INFO     This is wgd v2.0.38                       cli.py:34
                    INFO     Checking cores and threads...            core.py:35
                    INFO     The number of logical CPUs/Hyper         core.py:36
                             Threading in the system: 128                       
                    INFO     The number of physical cores in the      core.py:37
                             system: 64                                         
                    INFO     The number of actually usable CPUs in    core.py:38
                             the system: 15                                     
                    INFO     Checking memory...                       core.py:40
                    INFO     Total physical memory: 503.4771 GB       core.py:41
                    INFO     Available memory: 275.9073 GB            core.py:42
                    INFO     Free memory: 246.2832 GB                 core.py:43
2024-08-23 12:50:52 INFO     Configuring I-ADHoRe co-linearity search cli.py:703
                    INFO     Writing families file                     syn.py:96
                    INFO     Writing gene lists                        syn.py:98
2024-08-23 12:50:53 INFO     Writing config file                      syn.py:100
2024-08-23 12:50:54 INFO     Running I-ADHoRe                         cli.py:707
```

and stderr:

```
Traceback (most recent call last):
  File "/apps/eb/wgd/2.0.38-foss-2020b/bin/wgd", line 8, in <module>
    sys.exit(cli())
  File "/apps/eb/wgd/2.0.38-foss-2020b/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/apps/eb/wgd/2.0.38-foss-2020b/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/apps/eb/wgd/2.0.38-foss-2020b/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/apps/eb/wgd/2.0.38-foss-2020b/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/apps/eb/wgd/2.0.38-foss-2020b/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/apps/eb/wgd/2.0.38-foss-2020b/lib/python3.8/site-packages/cli.py", line 669, in syn
    _syn(**kwargs)
  File "/apps/eb/wgd/2.0.38-foss-2020b/lib/python3.8/site-packages/cli.py", line 708, in _syn
    run_adhore(conf)
  File "/apps/eb/wgd/2.0.38-foss-2020b/lib/python3.8/site-packages/wgd/syn.py", line 187, in run_adhore
    completed = sp.run(['i-adhore', config_file], stderr=sp.PIPE, stdout=sp.PIPE)
  File "/apps/eb/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/apps/eb/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/apps/eb/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'i-adhore'
```

TIA for your help troubleshooting!

**Comment by heche-psb** [comment]
Hi, it seems that you didn't install `i-adhore`. Please refer to the [documentation](https://github.com/VIB-PSB/i-ADHoRe) of `i-adhore` for a proper installation.
