### ISSUE TITLE
wgd peaks - IndexError: list index out of range

### ISSUE THREAD

**Issue by erika-r-moore** [heche-psb/wgd#47]
Hello! I am trying to date WGD events across eight taxa. I have successfully gone through `wgd dmd`, `wgd ksd`, and `wgd syn`, but when I run `wgd peaks` as a loop:
```
while read name;
do
wgd peak --heuristic ./wgd_ksd/$name.cds.tsv.ks.tsv -ap ./wgd_syn/iadhore-out/anchorpoints.txt -sm ./wgd_syn/iadhore-out/segments.txt -le ./wgd_syn/iadhore-out/list_elements.txt -mp ./wgd_syn/iadhore-out/multiplicon_pairs.txt -n 1 4 -kc 3 -o wgd_peak;
done < namelist.txt
```

I get the following error:
```
/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
Traceback (most recent call last):
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/bin/wgd", line 8, in <module>
    sys.exit(cli())
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/cli.py", line 351, in peak
    _peak(**kwargs)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/cli.py", line 373, in _peak
    df_ap = fit_apgmm_ap(hdr,anchorpoints,ksdf_filtered,seed,components,em_iter,n_init,outdir,method,gamma,weighted,plot,cutoff = kscutoff,peak_threshold=prominence_cutoff,rel_height=rel_height,user_xlim=xlim,user_ylim=ylim)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/wgd/peak.py", line 1834, in fit_apgmm_ap
    if method == 'gmm': models, aic, bic, besta, bestb, N = fit_gmm(out_file, X_log, seed, components[0], components[1], em_iter=em_iter, n_init=n_init)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/wgd/peak.py", line 761, in fit_gmm
    models[i-n1] = mixture.GaussianMixture(n_components = i, covariance_type='full', max_iter = em_iter, n_init = n_init, random_state = seed).fit(X)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/sklearn/mixture/_base.py", line 193, in fit
    self.fit_predict(X, y)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/sklearn/mixture/_base.py", line 220, in fit_predict
    X = _check_X(X, self.n_components, ensure_min_samples=2)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/sklearn/mixture/_base.py", line 57, in _check_X
    % (n_components, X.shape[0]))
ValueError: Expected n_samples >= n_components but got n_components = 4, n_samples = 3
/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
Traceback (most recent call last):
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/bin/wgd", line 8, in <module>
    sys.exit(cli())
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/cli.py", line 351, in peak
    _peak(**kwargs)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/cli.py", line 377, in _peak
    find_mpeak(df_ap_mp,anchorpoints,os.path.basename(ks_distribution),outdir,guide,peak_threshold=prominence_cutoff,rel_height=rel_height,ci=ci,user_low=kstodate[0],user_upp=kstodate[1],user=manualset,kscutoff=kscutoff,keeptmp=keeptmpfig)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/wgd/peak.py", line 1269, in find_mpeak
    lower95CI,upper95CI = plot_95CI_lognorm_hist(init_means, init_stdevs, ks_or, w, outdir, False, sp, ci=ci,guide=guide,keeptmp=True)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/wgd/peak.py", line 1511, in plot_95CI_lognorm_hist
    ax.plot(x_points_strictly_positive,scaling*stats.lognorm.pdf(x_points_strictly_positive, scale=np.exp(mean),s=std), c=cs[i], ls='-', lw=1.5, alpha=0.8, label='Peak {} mode {:.2f}'.format(i+1,np.exp(mean - std**2)))
IndexError: list index out of range
```

The error seems somewhat similar to #31. So, I tried to check my wgd version and I am using version 2.0.38, so I don't believe it is the same issue.

Do you know why I am getting this error? I would be happy to send my input files through email if needed. The files ended up being too large to attach to this issue.

Thanks!

Best,
Erika

**Comment by heche-psb** [comment]
Hi, you may send me your input files via a google drive link or other link. My psb email doesn't have enough storage now. I will try to reproduce your error.

**Comment by erika-r-moore** [comment]
Hello! Thank you for responding so quickly! I have put a tarred folder of my input data in [GoogleDrive](https://drive.google.com/drive/folders/1knJeg6lXXhMXqYSKbvlMFfOQB4fkR2ws?usp=sharing).

**Comment by heche-psb** [comment]
Hi, `wgd peak` should run on each species's collinear results and Ks separately. But you're using the same collinear results for different species.

**Comment by erika-r-moore** [comment]
I did not realize that! Thank you for bringing that to my attention!

I kept my `wgd_dmd` and `wgd_ksd` files as is, but re-ran `wgd_syn` and `wgd_peak` by generating separate species folders for each run:

```
#syn:
while read name;
do
wgd syn -f mRNA ./wgd_dmd/$name.cds.tsv ./"$name"_braker.gff3 -ks ./wgd_ksd/$name.cds.tsv.ks.tsv -o wgd_syn_"$name";
done < namelist.txt

#peak: 
while read name;
do
wgd peak --heuristic ./wgd_ksd/$name.cds.tsv.ks.tsv -ap ./wgd_syn_"$name"/iadhore-out/anchorpoints.txt -sm ./wgd_syn_"$name"/iadhore-out/segments.txt -le ./wgd_syn_"$name"/iadhore-out/list_elements.txt -mp ./wgd_syn_"$name"/iadhore-out/multiplicon_pairs.txt -n 1 4 -kc 3 -o wgd_peak_"$name";
done < namelist.txt
```

It looks like `wgd peak` fails only at the last sample (Scaevola) as that is the only `wgd_peak_"$name"/SegmentKs_FindPeak/` folder that is empty. The full error message is below:

```
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/63433', please create it with 0700 permissions.
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/63433', please create it with 0700 permissions.
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/63433', please create it with 0700 permissions.
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/63433', please create it with 0700 permissions.
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/63433', please create it with 0700 permissions.
/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
Traceback (most recent call last):
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/bin/wgd", line 8, in <module>
    sys.exit(cli())
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/cli.py", line 351, in peak
    _peak(**kwargs)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/cli.py", line 377, in _peak
    find_mpeak(df_ap_mp,anchorpoints,os.path.basename(ks_distribution),outdir,guide,peak_threshold=prominence_cutoff,rel_height=rel_height,ci=ci,user_low=kstodate[0],user_upp=kstodate[1],user=manualset,kscutoff=kscutoff,keeptmp=keeptmpfig)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/wgd/peak.py", line 1269, in find_mpeak
    lower95CI,upper95CI = plot_95CI_lognorm_hist(init_means, init_stdevs, ks_or, w, outdir, False, sp, ci=ci,guide=guide,keeptmp=True)
  File "/home/ermoore3/miniconda2/envs/mamba/envs/wgdv2/lib/python3.6/site-packages/wgd/peak.py", line 1511, in plot_95CI_lognorm_hist
    ax.plot(x_points_strictly_positive,scaling*stats.lognorm.pdf(x_points_strictly_positive, scale=np.exp(mean),s=std), c=cs[i], ls='-', lw=1.5, alpha=0.8, label='Peak {} mode {:.2f}'.format(i+1,np.exp(mean - std**2)))
IndexError: list index out of range
```

I updated my [GoogleDrive](https://drive.google.com/drive/folders/1knJeg6lXXhMXqYSKbvlMFfOQB4fkR2ws?usp=drive_link) with the input files specifically for Scaevola and the `wgd_peak` output folder. 

Is there something else that I am missing? Or, is there something wrong specifically with that sample?

Thanks for any help you can provide!

Best,
Erika

**Comment by heche-psb** [comment]
Hi, could you please check the collinearity result of your "Scaevola" dataset? If the retained collinearity is scarce, it's meanless to use `wgd peak` to find signals of WGD events.

**Comment by erika-r-moore** [comment]
I'm sorry for not responding sooner! It **was** that the collinearity was too scarce for `wgd peak`. I appreciate your input!
