### ISSUE TITLE
wdg viz -d wgd_globalmrbh_ks/ error:  ValueError: `dataset` input should have multiple elements.

### ISSUE THREAD

**Issue by YingLiPUMC** [heche-psb/wgd#48]
when I tried this commond: wgd viz -d wgd_globalmrbh_ks/global_MRBH.tsv.ks.tsv -fa Aquilegia_coerulea -epk wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv -ap wgd_syn/iadhore-out/anchorpoints.txt -sp speciestree.nw -o wgd_viz_mixed_Ks --plotelmm --plotapgmm --reweight
I got the error as following:
Traceback (most recent call last):
  File "/home/yli/anaconda3/envs/mamba_base/envs/wgd/bin/wgd", line 10, in <module>
    sys.exit(cli())
  File "/home/yli/anaconda3/envs/mamba_base/envs/wgd/lib/python3.8/site-packages/click/core.py", line 829, in __c  all__
    return self.main(*args, **kwargs)
  File "/home/yli/anaconda3/envs/mamba_base/envs/wgd/lib/python3.8/site-packages/click/core.py", line 782, in mai  n
    rv = self.invoke(ctx)
  File "/home/yli/anaconda3/envs/mamba_base/envs/wgd/lib/python3.8/site-packages/click/core.py", line 1259, in in  voke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yli/anaconda3/envs/mamba_base/envs/wgd/lib/python3.8/site-packages/click/core.py", line 1066, in in  voke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yli/anaconda3/envs/mamba_base/envs/wgd/lib/python3.8/site-packages/click/core.py", line 610, in inv  oke
    return callback(*args, **kwargs)
  File "/home/yli/anaconda3/envs/mamba_base/envs/wgd/lib/python3.8/site-packages/cli.py", line 478, in ksd
    _ksd(**kwargs)
  File "/home/yli/anaconda3/envs/mamba_base/envs/wgd/lib/python3.8/site-packages/cli.py", line 532, in _ksd
    multi_sp_plot(df,spair,spgenemap,outdir,onlyrootout,title=prefix,ylabel=ylabel,ksd=True,reweight=reweight,spt  ree=speciestree,extraparanomeks=extraparanomeks, ap = anchorpoints,plotkde=plotkde,plotapgmm=plotapgmm,plotelmm=p  lotelmm,components=components,na=node_average,user_xlim=xlim,user_ylim=ylim,adjustortho=adjustortho,adfactor=adju  stfactor,okalpha=okalpha,focus2all=focus2all,clean=classic)
  File "/home/yli/anaconda3/envs/mamba_base/envs/wgd/lib/python3.8/site-packages/wgd/viz.py", line 625, in multi_  sp_plot
    ratediffplot(df,outdir,focus2all,sptree,onlyrootout,reweight,extraparanomeks,ap,na=na,elmm=plotelmm,mEM=max_E  M_iterations,nEM=num_EM_initializations,pt=peak_threshold,rh=rel_height,components=components,apgmm=plotapgmm)
  File "/home/yli/anaconda3/envs/mamba_base/envs/wgd/lib/python3.8/site-packages/wgd/ratecorrect.py", line 784, i  n ratediffplot
    getspairplot_cov_cor(df,focusp,speciestree,onlyrootout,reweight,extraparanomeks,anchorpoints,outdir,na=na,elm  m=elmm,mEM=mEM,nEM=nEM,pt=pt,rh=rh,components=components,apgmm=apgmm)
  File "/home/yli/anaconda3/envs/mamba_base/envs/wgd/lib/python3.8/site-packages/wgd/ratecorrect.py", line 746, i  n getspairplot_cov_cor
    fig,spairs_means_stds_samples,ax_spair,maxim_spair,ks_spair,ax_spair_fp,fig_fp,fig_sigs,ax_sigs = plotspair_c  ov(df,all_spairs,spairs,focusp,reweight,na=na)
  File "/home/yli/anaconda3/envs/mamba_base/envs/wgd/lib/python3.8/site-packages/wgd/ratecorrect.py", line 590, i  n plotspair_cov
    kde = stats.gaussian_kde(y,weights=w,bw_method=0.1)
  File "/home/yli/anaconda3/envs/mamba_base/envs/wgd/lib/python3.8/site-packages/scipy/stats/kde.py", line 193, i  n __init__
    raise ValueError("`dataset` input should have multiple elements.")
ValueError: `dataset` input should have multiple elements.

What can I do to fix it. 
Please help me and thank you very much.

Ying

**Comment by heche-psb** [comment]
Hi, the error log indicated that your `wgd_globalmrbh_ks/global_MRBH.tsv.ks.tsv`  datafile didn't have corresponding data for the species pair in your `speciestree.nw` file. Could you please share the content of these two files?
