### ISSUE TITLE
wgd sync

### ISSUE THREAD

**Issue by Bio1nform** [heche-psb/wgd#7]
Hi, 
This question was solved.
Thanks

**Comment by Bio1nform** [comment]
Hi, 
This is working,

But new error with : **wgd ksd wgd_globalmrbh/global_MRBH.tsv --extraparanomeks wgd_ksd/Aquilegia_coerulea.tsv.ks.tsv -sp speciestree.nw --reweight -o wgd_globalmrbh_ks1 --spair "Aquilegia_coerulea;Protea_cynaroides" --spair "Aquilegia_coerulea;Vitis_vinifera" --spair "Aquilegia_coerulea;Acorus_americanus" --spair "Aquilegia_coerulea;Aquilegia_coerulea" --plotkde -ap wgd_syn/iadhore-out/anchorpoints.txt Aquilegia_coerulea Protea_cynaroides Acorus_americanus Vitis_vinifera**

/home/.conda/envs/wgd2/lib/python3.8/site-packages/Bio/Seq.py:2855: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(
Traceback (most recent call last):
  File "/home/.conda/envs/wgd2/bin/wgd", line 10, in <module>
    sys.exit(cli())
  File "/home/.conda/envs/wgd2/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/.conda/envs/wgd2/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/.conda/envs/wgd2/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/.conda/envs/wgd2/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/.conda/envs/wgd2/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/.conda/envs/wgd2/lib/python3.8/site-packages/cli.py", line 449, in ksd
    _ksd(**kwargs)
  File "/home/.conda/envs/wgd2/lib/python3.8/site-packages/cli.py", line 487, in _ksd
    if len(spair)!= 0:  multi_sp_plot(df,spair,spgenemap,outdir,onlyrootout,title=prefix,ylabel=ylabel,ksd=True,reweight=reweight,sptree=speciestree,extraparanomeks=extraparanomeks, ap = anchorpoints,plotkde=plotkde,plotapgmm=plotapgmm,plotelmm=plotelmm,components=components)
  File "/home/.conda/envs/wgd2/lib/python3.8/site-packages/wgd/viz.py", line 537, in multi_sp_plot
    ax.quiver(mode,maxim*scale, corrected_ks_spair[pair]-mode, 0, angles='xy', scale_units='xy', scale=1,color=cs[i],width=0.005,headwidth=2,headlength=2,headaxislength=2)
NameError: name 'scale' is not defined

Thanks

**Comment by heche-psb** [comment]
Same with my last reply, could you make sure the latest version in the github repository is installed for your `wgd v2`?
